### PR TITLE
Labels params added

### PR DESCRIPTION
**Pull request by JennLeon**
Labels params added

[Related issue](https://github.com/mineiros-io/terraform-google-bigquery-dataset/issues/12)

@mariux

### CODE REVIEW

**Review by soerenmartius — APPROVED** [review]
lgtm, thanks for providing this fix. I will create a new release in a little while

**Comment by mariux** [comment]
we need to update the test suite ;) @waxb will try to do so..

**Comment by JennLeon** [comment]
Hey @mineiros-team @mariux @waxb hope is all good, i wanna understand whats missing for this PR?

**Comment by mariux** [comment]
cont. in https://github.com/mineiros-io/terraform-google-bigquery-dataset/pull/18 to make tests run r4r ;)

**Pull request closed without merging**
